### ISSUE TITLE
Error in `$<-.data.frame`(`*tmp*`, group_names, value = "MGC1.peak_38.bed") :    替换数据里有1行，但数据有0

### ISSUE THREAD

**Issue by Leo-Huang123** [junjunlab/metaplot#1]
输入bed文件后
meta <- metaPlot(bed_file = "M1.peak_38.bed",
                 features_anno = feature_anno)
报错

**Comment by junjunlab** [comment]
请保证你的bed文件染色体和注释文件的染色体一致，都有chr前缀或者都没有。

**Comment by Leo-Huang123** [comment]
> 请保证你的bed文件染色体和注释文件的染色体一致，都有chr前缀或者都没有。

换了注释文件后（gencode.v46.annotation.gtf.gz）可以作图，但是只能做出CDS区域。并且使用归一化命令的时候提示：
Error in `scale_x_continuous()`:
! `breaks` and `labels` must have the same length.
Run `rlang::last_trace()` to see where the error occurred.

**Comment by junjunlab** [comment]
使用**prepare_features**函数时你需要指定gtf注释文件里的**feature**内容，具体你需要查看自己的gtf文件，下面是个例子：

```
feature_anno <- prepare_features(gtf_file = "hg19.ncbiRefSeq.gtf.gz",
                                 features_name = c("5UTR","CDS","3UTR"))
```
